export class StationStatistics {
    LocationExternalId!: string;
    PaymentMethod!: number | null;
    SuccessRate7DStr!: string;
    SuccessRate7D!: number;
    SuccessTransactions7D!: number;
    FailTransactions7D!: number;
    CancelTransactions7D!: number;
    SuccessRate30DStr!: string;
    SuccessRate30D!: number;
    SuccessTransactions30D!: number;
    FailTransactions30D!: number;
    CancelTransactions30D!: number;
    SuccessRate90DStr!: string;
    SuccessRate90D!: number;
    SuccessTransactions90D!: number;
    FailTransactions90D!: number;
    CancelTransactions90D!: number;
    SuccessRateBeforeP97Str!: string;
    SuccessRateBeforeP97!: number;
    SuccessTransactions90DBeforeP97!: number;
    FailTransactions90DBeforeP97!: number;
    SuccessRateAfterP97Str!: string;
    SuccessRateAfterP97!: number;
    SuccessTransactionsAfterP97!: number;
    FailTransactionsAfterP97!: number;
    Gallons7D!: number;
    TotalSale7D!: number;
    Gallons30D!: number;
    TotalSale30D!: number;
    Gallons90D!: number;
    TotalSale90D!: number;
    CreatedAt!: string;
    Id!: number;
    UpdatedAt!: string | null;
    MPPA!: string;
    LastSwitchedToP97At!: string | null;
    State!: string;
    IsLoyalty!: boolean;
    ExtraMile!: boolean;
    MobilePayEnabled!: boolean;
    CTRAvailable!: boolean;
    Receipts7D!: number;
    Receipts14D!: number;
    ReceiptsCTROffline7D!: number;
    ReceiptsCTROffline14D!: number;
    ReceiptsCTRHasPoints7D!: number;
    ReceiptsCTRHasPoints14D!: number;
    ReceiptsCTRNoPoints7D!: number;
    ReceiptsCTRNoPoints14D!: number;
    ReceiptsCTRNotAvail7D!: number;
    ReceiptsCTRNotAvail14D!: number;

}